### ISSUE TITLE
Implementazione parser di sintassi SQL DDL

### ISSUE THREAD

**Issue by mattiarocchi** [asupdev/asup#59]
Implementare un parser di sintassi SQL DDL (qualora non fosse gia' disponibile) che implementi le seguenti istruzioni:

1. CALL
  - [x] Grammatica
  - [x] Modello

    - CALL P_MULT/PROC01 ('A', 1);
  
2. COMMIT
  - [x] Grammatica
  - [x] Modello

    - COMMIT;
    - COMMIT HOLD;

3. CONNECT
  - [x] Grammatica
  - [x] Modello

    - CONNECT;
    - CONNECT RESET;
    - CONNECT TO ASUP050 USER ASUP USING '';

4. CREATE ALIAS
  - [x] Grammatica
  - [x] Modello

    - CREATE ALIAS LIBRERIA1/NOME1 FOR LIBRERIA2/FILE2 (MEMBRO2);

5. CREATE INDEX
  - [x] Grammatica
  - [x] Modello

    - CREATE INDEX LIBRERIA1/INDEX1 ON LIBRERIA1/FILE1 (CAMPO1, CAMPO2);
    - CREATE UNIQUE INDEX LIBRERIA1/INDEX1 ON LIBRERIA1/FILE1 (CAMPO1 DESC, CAMPO2);

6. CREATE TABLE
  - [x] Grammatica
  - [x] Modello

    - CREATE TABLE LIBRERIA1/FILE1 (CAMPO1 FOR COLUMN NAME1 CHAR ( 10),
 CAMPO2 FOR COLUMN NAME2 DEC ( 10, 2));

    - CREATE TABLE LIBRERIA1/FILE1 (CAMPO1 FOR COLUMN NAME1 CHAR ( 10)
NOT NULL, CAMPO2 FOR COLUMN NAME2 DEC ( 10, 2) NOT NULL);

      - CREATE TABLE LIBRERIA1/FILE1 (CAMPO1 FOR COLUMN NAME1 CHAR (10 )
NOT NULL WITH DEFAULT, CAMPO2 FOR COLUMN NAME2 DECIMAL (10 , 2) NOT
NULL WITH DEFAULT);

7. CREATE VIEW
  - [x] Grammatica
  - [x] Modello

    - CREATE VIEW LIBRERIA1/MIAVISTA AS SELECT * FROM MUCONV0F WHERE 
MUCONT<>' '

      - CREATE VIEW LIBRERIA1/MIAVISTA (MUCONT, MULIBR, MUTIPO, MUOGGE,MUDESC, MUATTR, MUAPPL, MUMODU, MUUSCR, MUDTCR, MUORCR, MUDTMO,MUORMO, MUDTLS, MUGGLS, MULIVE, MUSTAT, MUGRAV, MUMESS, MUINFO,MUFILE, MUMEMB, MUDT01, MUDT02, MUDT03, MUDT04, MUDT05, MUCD01,MUCD02, MUCD03, MUCD04, MUCD05, MUNU01, MUNU02, MUNU03, MUNU04,MUNU05, MUFL01, MUFL02, MUFL03, MUFL04, MUFL05, MUFL06, MUFL07,MUFL08, MUFL09, MUFL10, MUUSES, MUDTES, MUORES, MUJOES) AS SELECT * FROM MUCONV0F WHERE MUCONT<>' '

8. DISCONNECT
  - [x] Grammatica
  - [x] Modello

    - DISCONNECT;
    - DISCONNECT CURRENT;
    - DISCONNECT ALL;

9. DROP ALIAS
  - [x] Grammatica
  - [x] Modello

    - DROP ALIAS LIBRERIA1/NOMEALT;

10. DROP INDEX
  - [x] Grammatica
  - [x] Modello

    - DROP INDEX LIBRERIA1/INDEX1;

11. DROP TABLE
  - [x] Grammatica
  - [x] Modello

    - DROP TABLE LIBRERIA1/MIATABLE CASCADE (Default)
    - DROP TABLE LIBRERIA1/MIATABLE RESTRICT

12. DROP VIEW
  - [x] Grammatica
  - [x] Modello

    - DROP VIEW LIBRERIA1/MIAVISTA CASCADE (Default);
    - DROP VIEW LIBRERIA1/MIAVISTA RESTRICT;

13. LOCK TABLE
  - [x] Grammatica
  - [x] Modello

    - LOCK TABLE LIBRERIA1/MIATABLE IN SHARE MODE (Default);
    - LOCK TABLE LIBRERIA1/MIATABLE IN EXCLUSIVE MODE;
    - LOCK TABLE LIBRERIA1/MIATABLE IN EXCLUSIVE MODE ALLOW READ;

14. RENAME
  - [x] Grammatica
  - [x] Modello

    - RENAME TABLE LIBRERIA1/MIATABLE TO NOME1 FOR SYSTEM NAME NOME2;
    - RENAME INDEX LIBRERIA1/MIOINDEX TO NOME1 FOR SYSTEM NAME NOME2;

15. RELEASE
  - [x] Grammatica
  - [x] Modello

    - RELEASE;
    - RELEASE CURRENT;
    - RELEASE ALL;

16. ROLLBACK
  - [x] Grammatica
  - [x] Modello

    - ROLLBACK;
    - ROLLBACK HOLD;

17. SET CONNECTION
  - [x] Grammatica
  - [x] Modello

    - SET CONNECTION MIODATABASE;

18. SET TRANSACTION
  - [x] Grammatica
  - [x] Modello

    - SET TRANSACTION ISOLATION LEVEL NO COMMIT;
    - SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED, READ WRITE;
    - SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
    - SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
    - SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

Verificare:
* Esistenza sintassi standard (ANSI 2003?)
* Token della grammatica gia' presenti nel modello [Eclipse DTP] (http://www.eclipse.org/datatools)
* Wizard IBMi -> STRSQL+F4

**Comment by darioforesti** [comment]
Parser completato.
